@Locadora.Api_HostAddress = http://localhost:5000

### Criar fabricante
POST {{Locadora.Api_HostAddress}}/api/fabricantes
Content-Type: application/json

{
    "nome": "Toyota",
    "paisOrigem": "Japão"
}